name: pombo_wallet
description: Global wallet.

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.2.0
  flutter_riverpod: ^2.4.10
  riverpod: ^2.5.0
  dotenv: ^4.2.0
  firebase_auth: ^4.16.0
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.24.2
  google_sign_in: ^6.1.6
  google_sign_in_web: ^0.12.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/pombo_logo.svg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Kiona
      fonts:
        - asset: assets/fonts/Kiona-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-VariableFont_wght.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 900
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
