// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW0ax54SQkPA12WCXuq0oV4sd1JuxdNMI',
    appId: '1:676753289149:web:5b02852ddeb09b52f72cd4',
    messagingSenderId: '676753289149',
    projectId: 'pombo-wallet',
    authDomain: 'pombo-wallet.firebaseapp.com',
    storageBucket: 'pombo-wallet.appspot.com',
    measurementId: 'G-4TSD0CCD42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr03jWtkFZd0H5UbEZ5AoiUiDnL8bR750',
    appId: '1:676753289149:android:85ea402a10cb3517f72cd4',
    messagingSenderId: '676753289149',
    projectId: 'pombo-wallet',
    storageBucket: 'pombo-wallet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTf0D_onngi3zMgX30RqNph8qpFN0ggPg',
    appId: '1:676753289149:ios:6b1ff4b4ad14df94f72cd4',
    messagingSenderId: '676753289149',
    projectId: 'pombo-wallet',
    storageBucket: 'pombo-wallet.appspot.com',
    iosBundleId: 'com.example.pomboWallet',
  );
}
